"""Interactive chat CLI backed by an executor model with the advisor tool wired in.

Leave this running in a terminal and type into it like a normal chat. Every
reply is generated by the (fast, cheap) executor model, which can consult
the (slower, smarter) advisor model mid-turn for planning or course
correction.

Usage:

    export ANTHROPIC_API_KEY=sk-ant-...
    python chat.py
    python chat.py --executor claude-haiku-4-5-20251001 --advisor claude-opus-4-8 --verbose

In-chat commands:
    /reset   clear conversation history
    /usage   print cumulative executor vs. advisor token usage
    /exit    quit (or Ctrl-D / Ctrl-C)
"""

import argparse
import sys

from advisor_tool import AdvisorToolClient, build_advisor_tool, summarize_usage, validate_pair
from advisor_tool.usage import UsageSummary

DEFAULT_SYSTEM_PROMPT = """\
You have access to an `advisor` tool backed by a stronger reviewer model. It takes NO \
parameters — when you call advisor(), your entire conversation history is automatically \
forwarded.

Call advisor BEFORE substantive work — before writing, before committing to an \
interpretation, before building on an assumption. Also call it when you believe a \
complex answer is complete, when stuck, or when considering a change of approach. On \
short, simple exchanges, just answer directly.
"""


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--executor", default="claude-sonnet-4-6", help="Executor model ID.")
    parser.add_argument("--advisor", default="claude-opus-4-8", help="Advisor model ID.")
    parser.add_argument("--system", default=DEFAULT_SYSTEM_PROMPT, help="System prompt for the executor.")
    parser.add_argument("--max-tokens", type=int, default=4096, help="Executor max_tokens per turn.")
    parser.add_argument("--advisor-max-tokens", type=int, default=None, help="Cap on advisor output tokens (min 1024).")
    parser.add_argument("--max-uses", type=int, default=None, help="Cap on advisor calls per request.")
    parser.add_argument("--caching-ttl", choices=["5m", "1h"], default=None, help="Enable advisor-side prompt caching.")
    parser.add_argument("--verbose", action="store_true", help="Print advisor text and per-turn usage.")
    return parser.parse_args()


def print_turn(content, verbose: bool) -> None:
    for block in content:
        block_type = getattr(block, "type", None)
        if block_type == "text":
            print(block.text)
        elif block_type == "server_tool_use" and getattr(block, "name", None) == "advisor":
            print("  [consulting advisor...]", file=sys.stderr)
        elif block_type == "advisor_tool_result":
            result = block.content
            result_type = getattr(result, "type", None)
            if result_type == "advisor_tool_result_error":
                print(f"  [advisor unavailable: {result.error_code}]", file=sys.stderr)
            elif verbose and result_type == "advisor_result":
                print(f"  [advisor] {result.text}", file=sys.stderr)
            else:
                print("  [advisor replied]", file=sys.stderr)


def add_summary(total: UsageSummary, part: UsageSummary) -> UsageSummary:
    return UsageSummary(
        executor_input_tokens=total.executor_input_tokens + part.executor_input_tokens,
        executor_output_tokens=total.executor_output_tokens + part.executor_output_tokens,
        advisor_input_tokens=total.advisor_input_tokens + part.advisor_input_tokens,
        advisor_output_tokens=total.advisor_output_tokens + part.advisor_output_tokens,
        advisor_calls=total.advisor_calls + part.advisor_calls,
    )


def print_usage(summary: UsageSummary) -> None:
    print(
        f"  executor tokens: {summary.executor_input_tokens} in / {summary.executor_output_tokens} out\n"
        f"  advisor calls: {summary.advisor_calls} "
        f"({summary.advisor_input_tokens} in / {summary.advisor_output_tokens} out)",
        file=sys.stderr,
    )


def main() -> None:
    args = parse_args()
    try:
        validate_pair(args.executor, args.advisor)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    tools = [
        build_advisor_tool(
            model=args.advisor,
            max_uses=args.max_uses,
            max_tokens=args.advisor_max_tokens,
            caching_ttl=args.caching_ttl,
        )
    ]
    client = AdvisorToolClient()
    messages = []
    total_usage = UsageSummary(0, 0, 0, 0, 0)

    print(f"executor={args.executor} advisor={args.advisor}  (/reset, /usage, /exit)", file=sys.stderr)

    while True:
        try:
            user_input = input("\nyou> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not user_input:
            continue
        if user_input == "/exit":
            break
        if user_input == "/reset":
            messages = []
            print("  [history cleared]", file=sys.stderr)
            continue
        if user_input == "/usage":
            print_usage(total_usage)
            continue

        messages.append({"role": "user", "content": user_input})

        while True:
            response = client.create(
                model=args.executor,
                max_tokens=args.max_tokens,
                system=args.system,
                tools=tools,
                messages=messages,
            )
            messages.append({"role": "assistant", "content": response.content})
            total_usage = add_summary(total_usage, summarize_usage(response.usage))

            print_turn(response.content, args.verbose)

            if response.stop_reason == "pause_turn":
                # Advisor call still pending; resend as-is to let the API finish it.
                continue
            break

        if args.verbose:
            print_usage(summarize_usage(response.usage))


if __name__ == "__main__":
    main()
